// Generated by CoffeeScript 1.6.3
var app;

app = angular.module('geomoment');

app.filter('addTime', [
  'geomoment', function(geomoment) {
    return function(timestamp, key, amount) {
      return geomoment(timestamp).add(key, amount).toDate();
    };
  }
]);
