// Generated by CoffeeScript 1.6.3
var app;

app = angular.module('geomoment');

app.filter('date', function() {
  return function() {
    throw Error('Please use `formatDate` instead of `date`.');
  };
});
