// Generated by CoffeeScript 1.6.3
var app, formatDate,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

app = angular.module('geomoment');

formatDate = require('../helpers/format_date');

app.filter('formatDate', [
  'geomoment', function(geomoment) {
    return function(date, tzid, outFormat) {
      if (date == null) {
        return '';
      }
      if (!tzid) {
        throw Error('tzid required');
      }
      if (__indexOf.call(Object.keys(geomoment.formats), outFormat) >= 0) {
        outFormat = geomoment.formats[outFormat];
      }
      return geomoment(date).tz(tzid).format(outFormat);
    };
  }
]);
