// Generated by CoffeeScript 1.6.3
var app, iso8601Regexp,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

app = angular.module('geomoment');

iso8601Regexp = /^(\d{4})-(\d{2})-(\d{2})[ T](\d{2})\:(\d{2})\:(\d{2})/;

app.filter('formatDate', [
  'geomoment', function(geomoment) {
    return function(date, tzid, outFormat) {
      var format, name, parsedDate;
      if (date == null) {
        return '';
      }
      if (!tzid) {
        throw Error('tzid required');
      }
      parsedDate = null;
      if (typeof date === 'string') {
        if (iso8601Regexp.test(date)) {
          parsedDate = geomoment(date);
        }
        if (!(parsedDate != null ? parsedDate.isValid() : void 0)) {
          if (__indexOf.call(Object.keys(geomoment.formats), outFormat) >= 0) {
            outFormat = geomoment.formats[outFormat];
          }
          parsedDate = geomoment(date, (function() {
            var _ref, _results;
            _ref = geomoment.formats;
            _results = [];
            for (name in _ref) {
              format = _ref[name];
              _results.push(format);
            }
            return _results;
          })());
        }
      } else {
        parsedDate = geomoment(date);
      }
      return parsedDate.tz(tzid).format(outFormat);
    };
  }
]);
