// Generated by CoffeeScript 1.6.3
var app,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

app = angular.module('geomoment');

app.filter('formatDay', [
  'geomoment', function(geomoment) {
    return function(day, outFormat) {
      if (__indexOf.call(Object.keys(geomoment.formats), outFormat) >= 0) {
        outFormat = geomoment.formats[outFormat];
      }
      return geomoment.day(day, geomoment.pacific.tzid).format(outFormat);
    };
  }
]);
