// Generated by CoffeeScript 1.6.3
var app, geomoment;

geomoment = require('geomoment/lib/client');

app = angular.module('geomoment');

app.factory('geomoment', function() {
  return geomoment;
});
