// Generated by CoffeeScript 1.6.3
var app, formatDate, geomoment,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

geomoment = require('geomoment/lib/client');

app = angular.module('geomoment', []);

formatDate = function(dateMoment, outFormat) {
  if (__indexOf.call(Object.keys(geomoment.formats), outFormat) >= 0) {
    outFormat = geomoment.formats[outFormat];
  }
  return dateMoment.format(outFormat);
};

app.filter('date', function() {
  return function() {
    throw Error('Please use `formatDate` instead of `date`.');
  };
});

app.filter('formatDate', function() {
  return function(date, tzid, outFormat) {
    if (date == null) {
      return '';
    }
    if (!tzid) {
      throw Error('tzid required');
    }
    return formatDate(geomoment(date).tz(tzid), outFormat);
  };
});

app.filter('formatDay', function() {
  return function(day, outFormat) {
    return formatDate(geomoment.day(day, geomoment.pacific.tzid), outFormat);
  };
});

app.factory('geomoment', function() {
  return geomoment;
});

app;
